### ISSUE TITLE
JOSS Review Overview

### ISSUE THREAD

**Issue by j-andrews7** [ialbert/genescape-central#2]
I am going to keep a list/links to individual issues here for the JOSS review to help keep things organized for myself as I go through. This is well put together - much of this will be stuff that I'd like to see as a user and a few things that stand out from the developer side.

I'll ping you here when I am done with my initial review.

Should be done:

- [x] Minor text edits & cite networkx - #3 
- [x] Fix duplicate inputs bug - #8 
- [x] Custom GAF index use unclear - #12 
- [x] Document custom index should be made from gzipped GAF - #11 

Would prefer to see done:

- [x] Host web server - #4
- [x] Utilize `bottle` via imports rather than inclusion in source - #5
- [x] High resolution image download from GUI - #6 
- [x] Download annotations table directly from GUI - #10 
- [x] Leaf node coloring when filtering applied - #13 

Worth considering:

- [x] Support other gene identifiers - #7

Nitpicks/oddities:

- [x] Input box resizing - #9

**Comment by j-andrews7** [comment]
Alright @ialbert, I think I'm done with a first pass. All of my points have individual issues, so I'm happy to discuss any of them individually. Many are quick fixes, a few are questions - just let me know if anything is unclear.

**Comment by ialbert** [comment]
@j-andrews7 all issues addressed, 

thanks for the suggestion for using Shiny - it worked out really well and I learned a new skill, that of developing Shiny apps with Python.

**Comment by j-andrews7** [comment]
Okay, I'm pretty happy with the changes. Will mark my review complete over on the JOSS issue as well. Nice job on the quick fixes.
